const Symbols = [
  { name: "scorn", path: "2 - EFqY2PV.png" },
  { name: "hive", path: "3 - BqhXIKU.png" },
  { name: "witness", path: "4 - RwpNfLH.png" },
  { name: "guardian", path: "5 - Qst3vIf.png" },
  { name: "savathun", path: "6 - zHEg8A4.png" },
  { name: "black garden", path: "7 - E2f2JMc.png" },
  { name: "tower", path: "8 - ST1TrgB.png" },
  { name: "earth", path: "9 - Bm7t9yp.png" },
  { name: "ascendant plane", path: "10 - 2U32xrl.png" },
  { name: "fleet", path: "11 - qy7ueGX.png" },
  { name: "pyramid", path: "12 - roME7e0.png" },
  { name: "traveler", path: "13 - NtIPlhW.png" },
  { name: "worm", path: "14 - uP7a2ug.png" },
  { name: "black heart", path: "15 - KMGh6k1.png" },
  { name: "light", path: "16 - e2PRCzb.png" },
  { name: "neutral", path: "17 - HR1D3ai.png" },
  { name: "worship", path: "18 - ZC6SaK5.png" },
  { name: "drink", path: "19 - 5zIGKEL.png" },
  { name: "stop", path: "20 - JgyzFGl.png" },
  { name: "commune", path: "21 - tfUISJ7.png" },
  { name: "love", path: "22 - GigJnrj.png" },
  { name: "grief", path: "23 - 30VGMBS.png" },
  { name: "knowledge", path: "24 - TJraiof.png" },
  { name: "kill", path: "25 - 4L9IlQt.png" },
  { name: "give", path: "26 - WcNyuCC.png" },
  { name: "enter", path: "27 - IWPR7XF.png" },
];

export default Symbols;
